### ISSUE TITLE
Playing keyframes will also return the live replay to the point in time where the keyframes were created.

### ISSUE THREAD

**Issue by sugoikore** [SkinSpotlights/CreatorSuite-ReplayAPI#12]
Not sure if it's a bug or limitation from the replay api, I used the creatorsuite for cameras during streams and right now I'm not able to do that.

**Comment by SkinSpotlights** [comment]
Intended Feature.


There is plan to add in a new hotkey which will shift the keyframes to when the hotkey is pressed for broadcasts.
