### ISSUE TITLE
CAN NOT SET HOTKEYS

### ISSUE THREAD

**Issue by ugurkrdmr** [SkinSpotlights/CreatorSuite-ReplayAPI#13]
I can not set any hotkey. I don't know what to do. The view like this;

![Screenshot_11](https://user-images.githubusercontent.com/50177983/62428195-76f60700-b707-11e9-8197-d1e95a804e48.png)

**Comment by SkinSpotlights** [comment]
Double click on "None, None" and then the option to set the hotkey will appear.
