### ISSUE TITLE
Skybox doesn't work

### ISSUE THREAD

**Issue by thunder1141** [SkinSpotlights/CreatorSuite-ReplayAPI#14]
![캡처_2019_08_29_17_24_56_204](https://user-images.githubusercontent.com/54577913/63923780-18ac1200-ca82-11e9-968d-5be2b6655698.png)
![캡처_2019_08_29_17_25_42_855](https://user-images.githubusercontent.com/54577913/63923781-18ac1200-ca82-11e9-9a58-cfcd7b38c014.png)

I downloaded the Skybox image on https://www.skinspotlights.com/p/creator-suite.html
and applied it, but the sky is still black.
I don't know what caused this. Please help me
and I also added .dds on the image name But it doesn't work

(I'm not good at English. Please take that into consideration. I'm sorry)

**Comment by SkinSpotlights** [comment]
Graphical settings need to be set on max.

This is a requirement Riot have set in the ReplayAPI, I have no control over it.
