### ISSUE TITLE
Depth of field , keyframe , not working

### ISSUE THREAD

**Issue by M5TF** [SkinSpotlights/CreatorSuite-ReplayAPI#16]
Hello guys, the program doesn't work properly because when "Depth of field" is activated, the game closes and the "square clean" button is not active in the game. How to make a paused frame? My question is, how is the "Keyframe" active game paused?

**Comment by Adaliciously** [comment]
May I recommend finding a suitable title and using a standard font size? Maybe somebody will want to help you then

**Comment by M5TF** [comment]
What does it matter, is this not understandable?

**Comment by SkinSpotlights** [comment]
> when "Depth of field" is activated, the game closes

If the game is crashing then thats all on Riot to fix the issue.

> My question is, how is the "Keyframe" active game paused?

If you're talking about using keyframes while the game paused then currently thats not possible and unsure if it ever will, I need to test if you can effectively update the camera fast enough via the API to do it without stuttering or other issues.
