### ISSUE TITLE
Hide all characters and select which to show (enhancement)

### ISSUE THREAD

**Issue by JannaOneTrick** [SkinSpotlights/CreatorSuite-ReplayAPI#23]
Hi,
When hiding characters, many objects (considered characters somehow) still remain visible:
bushes / small animals / dragons / towers / nexus ...

I would like the ability to select which character I want on screen and which I want hidden.
Example:
I want to see only 1 champion on screen with nothing else but the skybox (for green screen purposes).

Thank you

**Comment by SkinSpotlights** [comment]
This request has to be put in with Riot.

The Replay API currently doesn't support being able to hide individual objects so I can't implement it.  You'd have to convince Riot to add the feature, considering they just ignored bugs I reported all I can say is good luck.
