### ISSUE TITLE
This new Spotlight Skin: CreatorSuite API does not have the same features as the old SkinSpotlight: CreatorSuite

### ISSUE THREAD

**Issue by leanbinh** [SkinSpotlights/CreatorSuite-ReplayAPI#24]
In the new version, the Spotlight Skin: CreatorSuite API doesn't have all the old features in SkinSpotlight: CreatorSuite (before patch 9.7). For example there is no fog color correction or map zooming like in the old version it lacks a lot of features and I can't edit the featured video without it. Can you add it to a new update or can you show me how to do it? thanks
(Sorry if my english is too bad)

old version ( before patch 9.7)
![179346398_958307458312007_1109127028298786860_n](https://user-images.githubusercontent.com/67872108/116671772-83d28800-a9cb-11eb-9f1f-d74ee5b59362.png)

new version
![179318167_188821526392851_106510998055681893_n](https://user-images.githubusercontent.com/67872108/116672907-eaa47100-a9cc-11eb-9c56-a90801d0440c.png)

**Comment by SkinSpotlights** [comment]
The left hand menu is scrollable and DOF/Fog options are further down.

Extended Zooming is a feature built into League itself, its ingame default hotkey is `ctrl shift z`.

This current version of the Creator Suite implement all the options available in Riots Replay API, any missing features from the original Creator Suite cannot be added unless you get Riot to implement the option in the Replay API.
