### ISSUE TITLE
Change Rift texture

### ISSUE THREAD

**Issue by JannaOneTrick** [SkinSpotlights/CreatorSuite-ReplayAPI#25]
Hello,
So when we play around with Creator Suite, we can change the skybox.
But could we change the rift texture?
Add a function to switch the rift from default to winter, summer, arid, volcanic...
Just like with skyboxes, we could add our own Rifts in a folder so it is available in the drop list in CreatorSuite.

Thanks

**Comment by SkinSpotlights** [comment]
You need to request this feature with Riot.

The ReplayAPI doesn't support anything like that therefore I can't implement it.
