### ISSUE TITLE
show announcer text  error

### ISSUE THREAD

**Issue by YELOFAN** [SkinSpotlights/CreatorSuite-ReplayAPI#26]
if  i  uncheak box [show ui] it make uncheak box[show announcer text}  is is good way work
but  i uncheak box [show ui] it make uncheak box[show announcer text} and i next when i cheak [show announcer text}box that is  now work = can.t see announcer text
if [show ui]box  cheaked,  that make can see announcer text /  but i  dont wanna see  ui and i wanna see text of announcer  
 how can fix that error   
i want to  not see  ui/see announcer text
plz explain to me how to  fix that

**Comment by SkinSpotlights** [comment]
Sounds like an issue that requires Riot attention.

I'm not Riot and have no contact with them, I can't do anything.
