### ISSUE TITLE
Muting item ping

### ISSUE THREAD

**Issue by JannaOneTrick** [SkinSpotlights/CreatorSuite-ReplayAPI#29]
I posted this issue 2 hours ago and it got closed without any answer and I wonder why...

I am at the moment watching one of my games and making a montage with in-game sounds.
I muted the ping, announcer and the music.

Then in the game client, I muted the "Sound FX" and it muted that specific sound I want to get rid of.
Although, it mutes almost every sounds in the game, like Champion spells etc...
So it cannot be the solution as I want those sounds in my montage.

Although, one of the players spammed item pings during the action I want to make my montage on.
He basically spam clicked the Flash of one of my team mates to alert his team that her Flash was on cooldown.

It makes a tchik tchik tchik sound (he did it 3 times) and it ruins the immersion of the clip I want to make.
I went through the particles list (I know there are some sounds inside) but I can't find that specific sound inside that list.

Please help me figure this out...

Thank you

**Comment by SkinSpotlights** [comment]
This github is for bugs with the tool.

This issue tab isn't for support with how to do things ingame or features that require Riots attention.
