### ISSUE TITLE
Skybox issue

### ISSUE THREAD

**Issue by JannaOneTrick** [SkinSpotlights/CreatorSuite-ReplayAPI#33]
Hello,
I knew what was the reason of this issue last year, it happened once and I solved it.
But I can't remember how now.

I created some skyboxes, by taking the default one, saved them in .dds,
I tried with and without generating mipmaps.
I tried 2d texture and cubemap.

I really don't know now

See attached pictures

Please help

![1](https://user-images.githubusercontent.com/53144454/176279053-36cb57c4-4dec-4094-b448-a9b0b25cadbb.png)
![2](https://user-images.githubusercontent.com/53144454/176279055-92d5430c-ad4a-47ae-a821-8f2c0fde684d.png)
![3](https://user-images.githubusercontent.com/53144454/176279061-70d22a07-580d-4071-a0fb-892a6d9dd3bf.png)

**Comment by SkinSpotlights** [comment]
Compression quality can't be anything above BC3 and image needs to be saved as a cubemap.
Example settings: https://cdn.discordapp.com/attachments/543089564974186497/983134662270537738/unknown.png
